### ISSUE TITLE
Milestone 1 To-do

### ISSUE THREAD

**Issue by jordanlau123** [UBC-MDS/pyeasytries#1]
- [x] Teamwork contract
 - [x] Topic
 - [x] Project structure for the python project
 - - [x] creat project structure under UBC-MDS organization
 - - [x] edit `CONTRIBUTORS.md` to add contributor names
 - - [x] edit `CONDUCT.md` to include code of conduct 
 - - [x] agree upon collaboration strategy (Github flow) and edit on `CONTRIBUTING.md`
 - - [x] High level summary of project in `README.md`
 - - [x] bulleted list of functions and 1-2 sentence description for each in `README.md`
 - - [x] paragraph describing where the pacakge fits into the python ecosystem in `README.md`
 - [x] Function specifications 
- - [x] 4 empty functions with appropriate function names
- - [x] Docstrings for functions
 - [x] Manage Issues 
- - [x] Project Boards & Milestones 
- - [x] create an issue for each function in the package (1 issue assigned for each team member)

**Comment by rainbowxyt0305** [comment]
Submitted Milestone 1 on canvas!
