### ISSUE TITLE
Package function: contain()

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/pyeasytries#14]

**Comment by shoebillm** [comment]
-  The function loops over the input word to check if every single letter from the word is present in the trie or not. 
-  The function also checks if the last letter has the `is_complete_word` label or not.
-  It returns `True` if the word is present (if both of the conditions above are satisfied)
-  It returns `False` if the word has not been stored in the trie

**Exception handling**
-  The input word must be a string, if not, the function will break and throw a `TypeError` message 
-  The input word must contain letters only, if not, the function will break and throw a `ValueError` message

**Comment by rainbowxyt0305** [comment]
Done by Mitchie. @shoebillm
