### ISSUE TITLE
Package function: delete() 

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/pyeasytries#17]

**Comment by rainbowxyt0305** [comment]
Done by Kaicheng. @Andrew-Tan

**Comment by Andrew-Tan** [comment]
### The function works as follows:

Given a word, delete that word from Trie if it exists.

### Exception handling
- The input word must be a string. If not, the function will throw a TypeError message
- The input word must not be empty. If not, the function will throw a ValueError message
